### ISSUE TITLE
PVD Delivery

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-boston/git-github-fork#11]
I taught this lesson immediately after the git basics one so again, tried not to deviate too much. 

- Just from past experience, I know that students have a hard time understanding local and remote repositories. I spent a good amount of time upfront talking about how what we did with git so far only applied to the code we have on our local machines. Then I asked, so what if we're working with others and want them to be able to access the code on their own machines or if somehow we lost  the code on our own machines..setting up the case for why we use github. I also showed them the photos from this DC lesson: https://github.com/ga-wdi-lessons/git-intro so they can visualize the process. 

- I didn't talk to them at all about `git remote add upstream`. I made a judgement call about that on the fly because I could tell they were already a good bit confused about what we had covered so far and we were running short on time and I wanted time to review. I think this would have confused them even more and it's also not a need to know at this stage. Instead, I showed them how to add each other as collaborators to a repo and work together on that repo. 

- Under the `editing on github` section, I'm not crazy about this language: "Wrong! DON'T EVER USE THAT!". It seems too strongly worded and opinionated to me. I like the next line: " Regardless of how small changes are you typically never want to edit ON GitHub. You always want to make changes locally and push them." Namely the use of the word "typically". I agree with this. Typically you don't want to do this, but there are times you might. Personally, I've done this more than a few times with readmes and it's simple enough to update your local to sync up with the remote.

**Comment by MicFin** [comment]
There are multiple issues in this single issue. I am going to recommend that this be closed and the issues be opened independently as such:

Re: Visuals https://github.com/ga-wdi-boston/git-github/issues/15
Re: Add Upstream https://github.com/ga-wdi-boston/git-github/issues/10
Re: Editing on Github https://github.com/ga-wdi-boston/git-github/issues/14
