### ISSUE TITLE
poorly named repository

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/git-github-fork#6]
doesn't encompass the fact that it includes push, pull, remote

**Comment by jrhorn424** [comment]
In my opinion this shouldn't include remotes. @gaand do you want to weigh in?

**Comment by jrhorn424** [comment]
I'd like to rename this `git-github`.

**Comment by berziiii** [comment]
@ga-wdi-boston/core renamed repo to 'git-github'. Can this be closed?

**Comment by berziiii** [comment]
Renamed and going to close this issue. Please reopen if need be. Thanks.
