### ISSUE TITLE
Creating an org?

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/git-github-fork#7]
Possibly include is it too early? @gaand

**Comment by jrhorn424** [comment]
No. Too early.

**Comment by berziiii** [comment]
@jrhorn424 okay to close since it's too early?

**Comment by gaand** [comment]
I assume this is covered in the unit 3 got thing.

**Comment by jrhorn424** [comment]
> I assume this is covered in the unit 3 got thing.

It is, in fact, covered in Unit 3.
