### ISSUE TITLE
Remote and local edit conflicts

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/git-github-fork#8]
- developer edits README.md on github
- developer edits local file and commits
- developer tries to push
- error occurs

**Comment by RealWeeks** [comment]
@berziiii Can you clarify this issue and the purpose? Is it just to have them run into conflicts? This sounds like a class cluster**. Did it work when you tried it?

**Comment by jrhorn424** [comment]
@berziiii What's the purpose of this? @payne-chris-r is blocked until we find out.

**Comment by payne-chris-r** [comment]
This should be fixed in latest commit.
